version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: face-timer-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: face_timer
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  # Uncomment this if you want to run the app in Docker
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: face-timer-app
  #   restart: always
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     NODE_ENV: development
  #     DB_HOST: postgres
  #     DB_PORT: 5432
  #     DB_USERNAME: postgres
  #     DB_PASSWORD: postgres
  #     DB_DATABASE: face_timer
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   command: npm run start:dev

volumes:
  postgres_data: